apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  ports:
    - port: 80
  type: NodePort
  selector:
    app: jupyter
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  containers:
    - name: jupyter
      image: skippbox/jupyter:0.0.1
      volumeMounts:
        - mountPath: /root
          name: notebook-volume
    - name: proxy
      image: kelseyhightower/kubectl:1.4.0
      args:
        - proxy
        - -p
        - "8080"
  volumes:
  - name: notebook-volume
    gitRepo:
      repository: "https://github.com/skippbox/notebooks.git"
